GET http://localhost:5286/games

###
GET http://localhost:5286/games/2

###
POST http://localhost:5286/games
Content-Type: application/json

{
    "name": "Super Mario Odyssey 3 Super Deluxe",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2017-10-27"
}

###
PUT http://localhost:5286/games/1
Content-Type: application/json


  {
    
    "name": "The Legend of Zelda: Breath of the Wild GOTY",
    "genre": "Action-Adventure",
    "price": 59.99,
    "releaseDate": "2017-03-03"
  }

###
DELETE http://localhost:5286/games/2